[package]
name = "test_consumer_crate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_consumer_crate"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.16", default-features = false, features = [
    "bevy_gltf",
    "bevy_winit",
    "bevy_render",
    "png",
    "web",
    "webgpu",
] }
bevy_mod_scripting = { default-features = false, features = [
    "rhai",
], path = "../../../../bevy_mod_scripting" }

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
