// @generated by cargo bevy-api-gen generate, modify the templates not this file
#![allow(clippy::all)]
#![allow(unused, deprecated, dead_code)]
#![cfg_attr(rustfmt, rustfmt_skip)]
use bevy_mod_scripting_core::bindings::{
    ReflectReference,
    function::{
        from::{Ref, Mut, Val},
        namespace::NamespaceBuilder,
    },
};
use bevy_mod_scripting_derive::script_bindings;
use crate::*;
pub struct BevyHierarchyScriptingPlugin;
#[script_bindings(
    remote,
    name = "children_functions",
    bms_core_path = "bevy_mod_scripting_core",
    generated
)]
impl bevy::prelude::Children {
    ///  Swaps the child at `a_index` with the child at `b_index`.
    fn swap(
        mut _self: Mut<bevy::prelude::Children>,
        a_index: usize,
        b_index: usize,
    ) -> () {
        let output: () = bevy::prelude::Children::swap(
                &mut _self,
                a_index,
                b_index,
            )
            .into();
        output
    }
}
#[script_bindings(
    remote,
    name = "parent_functions",
    bms_core_path = "bevy_mod_scripting_core",
    generated
)]
impl bevy::prelude::ChildOf {
    fn assert_receiver_is_total_eq(_self: Ref<bevy::prelude::ChildOf>) -> () {
        let output: () = <bevy::prelude::ChildOf as std::cmp::Eq>::assert_receiver_is_total_eq(
                &_self,
            )
            .into();
        output
    }
    fn eq(
        _self: Ref<bevy::prelude::ChildOf>,
        other: Ref<bevy::prelude::ChildOf>,
    ) -> bool {
        let output: bool = <bevy::prelude::ChildOf as std::cmp::PartialEq<
            bevy::prelude::ChildOf,
        >>::eq(&_self, &other)
            .into();
        output
    }
    ///  Gets the [`Entity`] ID of the parent.
    fn get(
        _self: Ref<bevy::prelude::ChildOf>,
    ) -> Val<bevy::ecs::entity::Entity> {
        let output: Val<bevy::ecs::entity::Entity> = bevy::prelude::ChildOf::get(
                &_self,
            )
            .into();
        output
    }
}
impl ::bevy::app::Plugin for BevyHierarchyScriptingPlugin {
    fn build(&self, app: &mut ::bevy::prelude::App) {
        let mut world = app.world_mut();
        register_children_functions(&mut world);
        register_parent_functions(&mut world);
    }
}
