// @generated by cargo bevy-api-gen generate, modify the templates not this file
#![allow(clippy::all)]
#![allow(unused, deprecated, dead_code)]
#![cfg_attr(rustfmt, rustfmt_skip)]
use super::bevy_ecs::*;
use super::bevy_reflect::*;
use super::bevy_core::*;
use bevy_mod_scripting_core::bindings::{
    ReflectReference,
    function::{
        from::{Ref, Mut, Val},
        namespace::NamespaceBuilder,
    },
};
use crate::*;
pub struct BevyHierarchyScriptingPlugin;
impl ::bevy::app::Plugin for BevyHierarchyScriptingPlugin {
    fn build(&self, app: &mut ::bevy::prelude::App) {
        let mut world = app.world_mut();
        NamespaceBuilder::<::bevy::hierarchy::prelude::Children>::new(world)
            .register(
                "swap",
                |
                    mut _self: Mut<bevy::hierarchy::prelude::Children>,
                    a_index: usize,
                    b_index: usize|
                {
                    let output: () = bevy::hierarchy::prelude::Children::swap(
                            &mut _self,
                            a_index,
                            b_index,
                        )
                        .into();
                    output
                },
            );
        NamespaceBuilder::<::bevy::hierarchy::prelude::Parent>::new(world)
            .register(
                "assert_receiver_is_total_eq",
                |_self: Ref<bevy::hierarchy::prelude::Parent>| {
                    let output: () = <bevy::hierarchy::prelude::Parent as std::cmp::Eq>::assert_receiver_is_total_eq(
                            &_self,
                        )
                        .into();
                    output
                },
            )
            .register(
                "eq",
                |
                    _self: Ref<bevy::hierarchy::prelude::Parent>,
                    other: Ref<bevy::hierarchy::prelude::Parent>|
                {
                    let output: bool = <bevy::hierarchy::prelude::Parent as std::cmp::PartialEq<
                        bevy::hierarchy::prelude::Parent,
                    >>::eq(&_self, &other)
                        .into();
                    output
                },
            );
        NamespaceBuilder::<::bevy::hierarchy::HierarchyEvent>::new(world)
            .register(
                "assert_receiver_is_total_eq",
                |_self: Ref<bevy::hierarchy::HierarchyEvent>| {
                    let output: () = <bevy::hierarchy::HierarchyEvent as std::cmp::Eq>::assert_receiver_is_total_eq(
                            &_self,
                        )
                        .into();
                    output
                },
            )
            .register(
                "clone",
                |_self: Ref<bevy::hierarchy::HierarchyEvent>| {
                    let output: Val<bevy::hierarchy::HierarchyEvent> = <bevy::hierarchy::HierarchyEvent as std::clone::Clone>::clone(
                            &_self,
                        )
                        .into();
                    output
                },
            )
            .register(
                "eq",
                |
                    _self: Ref<bevy::hierarchy::HierarchyEvent>,
                    other: Ref<bevy::hierarchy::HierarchyEvent>|
                {
                    let output: bool = <bevy::hierarchy::HierarchyEvent as std::cmp::PartialEq<
                        bevy::hierarchy::HierarchyEvent,
                    >>::eq(&_self, &other)
                        .into();
                    output
                },
            );
    }
}
