// @generated by cargo bevy-api-gen generate, modify the templates not this file
#![allow(clippy::all)]
#![allow(unused, deprecated, dead_code)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use bevy_mod_scripting_core::{
    bindings::{
        ReflectReference, 
        function::{from::{Ref, Mut, Val}, namespace::{NamespaceBuilder}}
    }
};

use bevy_mod_scripting_derive::script_bindings;


use crate::*;







pub struct BevySceneScriptingPlugin;


#[script_bindings(
    remote,
    name = "dynamic_scene_root_functions",
    bms_core_path="bevy_mod_scripting_core",
    generated
)]
impl bevy::scene::prelude::DynamicSceneRoot {


    
    fn assert_receiver_is_total_eq (_self:Ref<bevy::scene::prelude::DynamicSceneRoot>,) -> () {
        let output: () =<bevy::scene::prelude::DynamicSceneRoot as ::std::cmp::Eq>::assert_receiver_is_total_eq(&_self,).into();
        output
    }


    
    fn clone (_self:Ref<bevy::scene::prelude::DynamicSceneRoot>,) -> Val<bevy::scene::prelude::DynamicSceneRoot> {
        let output: Val<bevy::scene::prelude::DynamicSceneRoot> =<bevy::scene::prelude::DynamicSceneRoot as ::std::clone::Clone>::clone(&_self,).into();
        output
    }


    
    fn eq (_self:Ref<bevy::scene::prelude::DynamicSceneRoot>,other:Ref<bevy::scene::prelude::DynamicSceneRoot>,) -> bool {
        let output: bool =<bevy::scene::prelude::DynamicSceneRoot as ::std::cmp::PartialEq::<bevy::scene::prelude::DynamicSceneRoot>>::eq(&_self,&other,).into();
        output
    }
     
}

#[script_bindings(
    remote,
    name = "scene_root_functions",
    bms_core_path="bevy_mod_scripting_core",
    generated
)]
impl bevy::scene::prelude::SceneRoot {


    
    fn assert_receiver_is_total_eq (_self:Ref<bevy::scene::prelude::SceneRoot>,) -> () {
        let output: () =<bevy::scene::prelude::SceneRoot as ::std::cmp::Eq>::assert_receiver_is_total_eq(&_self,).into();
        output
    }


    
    fn clone (_self:Ref<bevy::scene::prelude::SceneRoot>,) -> Val<bevy::scene::prelude::SceneRoot> {
        let output: Val<bevy::scene::prelude::SceneRoot> =<bevy::scene::prelude::SceneRoot as ::std::clone::Clone>::clone(&_self,).into();
        output
    }


    
    fn eq (_self:Ref<bevy::scene::prelude::SceneRoot>,other:Ref<bevy::scene::prelude::SceneRoot>,) -> bool {
        let output: bool =<bevy::scene::prelude::SceneRoot as ::std::cmp::PartialEq::<bevy::scene::prelude::SceneRoot>>::eq(&_self,&other,).into();
        output
    }
     
}

#[script_bindings(
    remote,
    name = "scene_instance_ready_functions",
    bms_core_path="bevy_mod_scripting_core",
    generated
)]
impl bevy::scene::SceneInstanceReady {


    
    fn assert_receiver_is_total_eq (_self:Ref<bevy::scene::SceneInstanceReady>,) -> () {
        let output: () =<bevy::scene::SceneInstanceReady as ::std::cmp::Eq>::assert_receiver_is_total_eq(&_self,).into();
        output
    }


    
    fn clone (_self:Ref<bevy::scene::SceneInstanceReady>,) -> Val<bevy::scene::SceneInstanceReady> {
        let output: Val<bevy::scene::SceneInstanceReady> =<bevy::scene::SceneInstanceReady as ::std::clone::Clone>::clone(&_self,).into();
        output
    }


    
    fn eq (_self:Ref<bevy::scene::SceneInstanceReady>,other:Ref<bevy::scene::SceneInstanceReady>,) -> bool {
        let output: bool =<bevy::scene::SceneInstanceReady as ::std::cmp::PartialEq::<bevy::scene::SceneInstanceReady>>::eq(&_self,&other,).into();
        output
    }
     
}

#[script_bindings(
    remote,
    name = "instance_id_functions",
    bms_core_path="bevy_mod_scripting_core",
    generated
)]
impl bevy::scene::InstanceId {


    
    fn assert_receiver_is_total_eq (_self:Ref<bevy::scene::InstanceId>,) -> () {
        let output: () =<bevy::scene::InstanceId as ::std::cmp::Eq>::assert_receiver_is_total_eq(&_self,).into();
        output
    }


    
    fn clone (_self:Ref<bevy::scene::InstanceId>,) -> Val<bevy::scene::InstanceId> {
        let output: Val<bevy::scene::InstanceId> =<bevy::scene::InstanceId as ::std::clone::Clone>::clone(&_self,).into();
        output
    }


    
    fn eq (_self:Ref<bevy::scene::InstanceId>,other:Ref<bevy::scene::InstanceId>,) -> bool {
        let output: bool =<bevy::scene::InstanceId as ::std::cmp::PartialEq::<bevy::scene::InstanceId>>::eq(&_self,&other,).into();
        output
    }
     
}


impl ::bevy::app::Plugin for BevySceneScriptingPlugin {
    fn build(&self, app: &mut ::bevy::prelude::App) {
        let mut world = app.world_mut();

        
            register_dynamic_scene_root_functions(&mut world);
        
            register_scene_root_functions(&mut world);
        
            register_scene_instance_ready_functions(&mut world);
        
            register_instance_id_functions(&mut world);
        
    }
}
