name: Run benchmarks on PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_fork_pr_branch:
    name: Run PR Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          # reasoning: we want to cache xtask, most of the jobs in the matrix will be sped up a good bit thanks to that 
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-all-crates: true
      - name: Run `cargo xtask init`
        run: |
          cargo xtask init
      - name: Run `cargo xtask bench` and save results
        run: |
          cargo xtask bench > benchmark_results.txt
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_results.txt
          path: ./benchmark_results.txt
      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}