on:
  pull_request:
    branches:
      - "**"

name: Synchronize Bindings (Generate Diff)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generate_bindings:
    name: Diff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.7
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-all-crates: true
    - name: Setup
      run: |
        cargo xtask init
    - name: Generate Bindings
      run: |
        cargo xtask codegen
    - name: Check for changes and create diff
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> "$GITHUB_OUTPUT"
          git diff > bindings.diff
          echo "Diff created:"
          cat bindings.diff
        else
          echo "changes=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Upload Diff Artifact
      if: steps.check_changes.outputs.changes == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: bindings.diff
        path: bindings.diff
        retention-days: 1
    - name: Upload GitHub Pull Request Event
      uses: actions/upload-artifact@v4
      with:
        name: event-bindings.json
        path: ${{ github.event_path }}
    outputs:
      has-changes: ${{ steps.check_changes.outputs.changes }}
      pr-number: ${{ github.event.pull_request.number }}

  apply_bindings:
    name: Apply (Non-Fork Only)
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: generate_bindings
    if: github.event.pull_request.head.repo.full_name == github.repository && needs.generate_bindings.outputs.has-changes == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
    - name: Download diff artifact
      uses: actions/download-artifact@v4
      with:
        name: bindings-diff-${{ github.event.pull_request.number }}
    - name: Setup Bot GitHub Credentials
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Apply diff and commit
      run: |
        git apply bindings.diff
        git add -A
        git commit -m "chore(codegen): update bevy bindings"
        git push